[tool.cibuildwheel]
build = "cp3*"
skip = ["cp36-*", "cp37-*", "cp38-", "cp39-", "*-win32", "*-manylinux_i686", "*-musllinux_*"]
build-verbosity = 1
test-extras = ["testing"]
test-command = "python -m pytest {project}/tests"
